services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/sampledb
      - ACCESS_TOKEN_SECRET=TANLFDLFDFSDLF
      - REFRESH_TOKEN_SECRET=KDFDLFDFLSD
      - SMTP_EMAIL=tanmaychavan13@gmail.com
      - SMTP_PASSWORD=chexprzybzidtgvq
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
    driver: local
