services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules       # prevent local node_modules overwrite
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017
      - ACCESS_TOKEN_SECRET=TANLFDLFDFSDLF
      - REFRESH_TOKEN_SECRET=KDFDLFDFLSD
      - SMTP_EMAIL=tanmaychavan13@gmail.com
      - SMTP_PASSWORD=chexprzybzidtgvq
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
  node_modules: # This prevents conflict with host's node_modules
